### ISSUE TITLE
请教一下，前端如何判断没有使用应用了呢？

### ISSUE THREAD

**Issue by rebron1900** [ChingCdesu/ProcessReporterWin#3]
如题，Go语言版本是定时发起post请求，我之前是在前端通过判断如果2个轮次没有收到有用的数据就隐藏掉通知信息。
这个版本似乎是窗口激活的时候才发送数据，该如何实现这个判断好一些呢？

**Comment by rebron1900** [comment]
这个问题解决了。
目前切换过去的新窗口如果不在我的名单里我直接隐藏就好。

**Comment by ChingCdesu** [comment]
你可以添加一个定时器，比如5分钟没有再次上报就认为没有停留在应用界面了。
这一部分你可能需要参考Shiro的文档和源代码，做出相应的改动
