### ISSUE TITLE
每次窗口切换可以上传后台的音乐播放信息吗？

### ISSUE THREAD

**Issue by rebron1900** [ChingCdesu/ProcessReporterWin#4]
现在似乎只有在激活播放器的时候才会构建media对象。

**Comment by rebron1900** [comment]
我目前用的洛雪音乐，在是兼容windows的媒体接口的。
但是只要一切歌上报程序就会自动关闭，不知道程序的日志在哪里能看到？也许我可以贴一下日志出来。

**Comment by rebron1900** [comment]
另外缩小后再最大化后会提示，然后数据发送失败。
![image](https://github.com/ChingCdesu/ShiroProcessReporter/assets/7929884/0803ddc1-2d99-46f8-b301-d392d9cf5058)

**Comment by rebron1900** [comment]
> 我目前用的洛雪音乐，在是兼容windows的媒体接口的。 但是只要一切歌上报程序就会自动关闭，不知道程序的日志在哪里能看到？也许我可以贴一下日志出来。

新版本不会崩溃了，不过和上一条反馈一样，会频繁出现请求过多的问题。
![image](https://github.com/ChingCdesu/ShiroProcessReporter/assets/7929884/f98cfd88-59e4-4c9c-b76f-77ad6df82f2e)

**Comment by ChingCdesu** [comment]
网络错误可能是由于开了代理导致的，如果你使用的是Clash for Windows，你可以在`General`栏找到`UWP Loopback`，他会弹出一个窗口，其中选择上`ShiroProcessReporter`之后，按下顶部的`Save Changes`按钮，重启应用之后应该能解决。

如果你是使用的其他的代理软件，你可以在代理软件的设置界面寻找相似的配置项。

如果不能解决或者还有其他疑问，请留言

**Comment by rebron1900** [comment]
> 网络错误可能是由于开了代理导致的，如果你使用的是Clash for Windows，你可以在`General`栏找到`UWP Loopback`，他会弹出一个窗口，其中选择上`ShiroProcessReporter`之后，按下顶部的`Save Changes`按钮，重启应用之后应该能解决。
> 
> 如果你是使用的其他的代理软件，你可以在代理软件的设置界面寻找相似的配置项。
> 
> 如果不能解决或者还有其他疑问，请留言

我是路由器上用的小猫，开的Tun模式，应该不存在这种问题。

不过我还是尝试了你的这个办法，目前还是存在这个问题，尤其是在最大化、最小化窗口时会频繁出现这个错误提示，并且 `最小化再最大化后` 似乎焦点不会切换到最大化的窗口上，不会触发上报。

**Comment by ChingCdesu** [comment]
> 我是路由器上用的小猫，开的Tun模式，应该不存在这种问题。
> 
> 不过我还是尝试了你的这个办法，目前还是存在这个问题，尤其是在最大化、最小化窗口时会频繁出现这个错误提示，并且 `最小化再最大化后` 似乎焦点不会切换到最大化的窗口上，不会触发上报。

这个问题可能得抓个包看一下，或者你需要去看看路由器上Clash的日志，到服务走的是直连还是代理节点，以及代理节点或直连是否能正确访问服务器，检查每一个可能出现问题的网络节点，尝试用`curl -vvv https://your.domain`和`traceroute your.domain`诊断问题（这两个命令请在linux/freebsd上使用）

频繁出现最大化最小化的时候，windows内置的事件机制可能并不会将恢复后的窗口聚焦，因为他认为你只是恢复了这个窗口的位置，并非聚焦到此窗口，所以不会触发上报。

**Comment by rebron1900** [comment]
第一个问题我测试了一下，Clash的日志所有请求都是走的直连，应该没有问题。（是不是和nginx的配置有关系呢？
![image](https://github.com/ChingCdesu/ShiroProcessReporter/assets/7929884/cbff3cd5-046b-4ee1-b74d-18e64de74349)

nginx的配置，我这边是用的nginx，转发给内网容器

```
    location /update {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:3000/update;
    }
```

第二个问题应该是你说的这个逻辑，我在两个窗口之间点击窗口内容切换是可以正常触发。

但是经过我的测试：

1. 如果其中一个缩小了，再点击任务栏恢复后，即便鼠标点击了恢复后的窗口也不会触发上报。
2. 如果是通过最小化按钮缩小，再点击任务栏恢复后会触发上报

应该是通过任务栏缩小，再通过任务栏恢复就会出现这个问题。

**Comment by rebron1900** [comment]
另外，想本地调试一下，可以使用vscode来操作吗？（实在不想安装stuido，太臃肿了。。
我目前用vscode加C#工具包，安装了.net8.0依旧无法正常启动项目。
```
  已还原 d:\developer\ShiroProcessReporter\ShiroProcessReporter\ShiroProcessReporter\ShiroProcessReporter.csproj (用时 309 ms)。
C:\Users\1900\.nuget\packages\microsoft.windowsappsdk\1.5.240428000\buildTransitive\MrtCore.PriGen.targets(913,5): error MSB4062: 未能从程序集 C:\Program Files\dotnet\sdk\8.0.204\\Microsoft\VisualStudio\v17.0\AppxPackage\\Microsoft.Build.Packaging.Pri.Tasks.dll 加载任务“Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent”。Could not load file or assembly 'C:\Program Files\dotnet\sdk\8.0.204\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.Build.Packaging.Pri.Tasks.dll'. 系统找不到指定的路径。 请确认 <UsingTask> 声明正确，该程序集及其所有依赖项都可用，并且该任务包含实现 Microsoft.Build.Framework.ITask 的公共类。 [d:\developer\ShiroProcessReporter\ShiroProcessReporter\ShiroProcessReporter\ShiroProcessReporter.csproj]
```

**Comment by ChingCdesu** [comment]
> 另外，想本地调试一下，可以使用vscode来操作吗？（实在不想安装stuido，太臃肿了。。
> 我目前用vscode加C#工具包，安装了.net8.0依旧无法正常启动项目。
> ```
>   已还原 d:\developer\ShiroProcessReporter\ShiroProcessReporter\ShiroProcessReporter\ShiroProcessReporter.csproj (用时 309 ms)。
> C:\Users\1900\.nuget\packages\microsoft.windowsappsdk\1.5.240428000\buildTransitive\MrtCore.PriGen.targets(913,5): error MSB4062: 未能从程序集 C:\Program Files\dotnet\sdk\8.0.204\\Microsoft\VisualStudio\v17.0\AppxPackage\\Microsoft.Build.Packaging.Pri.Tasks.dll 加载任务“Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent”。Could not load file or assembly 'C:\Program Files\dotnet\sdk\8.0.204\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.Build.Packaging.Pri.Tasks.dll'. 系统找不到指定的路径。 请确认 <UsingTask> 声明正确，该程序集及其所有依赖项都可用，并且该任务包含实现 Microsoft.Build.Framework.ITask 的公共类。 [d:\developer\ShiroProcessReporter\ShiroProcessReporter\ShiroProcessReporter\ShiroProcessReporter.csproj]
> ```

这我也试过，但没成功

**Comment by rebron1900** [comment]
> > 另外，想本地调试一下，可以使用vscode来操作吗？（实在不想安装stuido，太臃肿了。。
> > 我目前用vscode加C#工具包，安装了.net8.0依旧无法正常启动项目。
> > ```
> >   已还原 d:\developer\ShiroProcessReporter\ShiroProcessReporter\ShiroProcessReporter\ShiroProcessReporter.csproj (用时 309 ms)。
> > C:\Users\1900\.nuget\packages\microsoft.windowsappsdk\1.5.240428000\buildTransitive\MrtCore.PriGen.targets(913,5): error MSB4062: 未能从程序集 C:\Program Files\dotnet\sdk\8.0.204\\Microsoft\VisualStudio\v17.0\AppxPackage\\Microsoft.Build.Packaging.Pri.Tasks.dll 加载任务“Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent”。Could not load file or assembly 'C:\Program Files\dotnet\sdk\8.0.204\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.Build.Packaging.Pri.Tasks.dll'. 系统找不到指定的路径。 请确认 <UsingTask> 声明正确，该程序集及其所有依赖项都可用，并且该任务包含实现 Microsoft.Build.Framework.ITask 的公共类。 [d:\developer\ShiroProcessReporter\ShiroProcessReporter\ShiroProcessReporter\ShiroProcessReporter.csproj]
> > ```
> 
> 这我也试过，但没成功；
Stuido那个大小我真不想安装，算了，等大佬有时间修把 。 😄
