### ISSUE TITLE
安装不了呢

### ISSUE THREAD

**Issue by ZtfCoder** [ChingCdesu/ProcessReporterWin#6]
无法验证此应用包的发布者证书。请与系统管理员或应用开发人员联系，以获取具有验证证书的新应用包。必须验证应用包中签名的根证书和所有直接证书(0x800B010A)

**Comment by ChingCdesu** [comment]
![image](https://github.com/user-attachments/assets/e17c6e4d-72de-4833-9c13-deb621830370)

**Comment by ChingCdesu** [comment]
证书在以前版本的Release中
